update logo and styling for the footer
TheEugeniaKim/humaniki pull request #3
Opened 2021-01-24 09:32 UTC by sejalkhatri

2021-01-24 20:01 UTC, notconfusing reviewed
Goold work @sejalkhatri 

<iframe src="https://giphy.com/embed/l41lHvfYqxWus1oYw" width="451" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/high-five-hi-hi-5-l41lHvfYqxWus1oYw">via GIPHY</a></p>

2021-01-24 20:01 UTC, notconfusing commented on package.json
> +    "start": "call env.bat && react-scripts start",
call env.bat
then
react-scripts-start

2021-01-24 20:01 UTC, notconfusing commented on src/App.css
> -  position: -webkit-sticky;
Just double checking, we are removing the stick footer?
I kind of like that decision.

2021-01-24 20:01 UTC, notconfusing commented on package.json
> +    "start": "call env.bat && react-scripts start",
Lets remove this modification.

2021-01-24 20:01 UTC, notconfusing commented on src/Components/FAQ.js
> +    // <Navbar sticky="bottom" className="footer">
delete this cruft

2021-01-24 20:01 UTC, notconfusing commented on src/Components/FAQ.js
> +    <div>
put Id on this Div

2021-01-24 20:01 UTC, notconfusing commented on src/Components/Footer.js
> +  			<div></div>
are these empty divs important?

2021-01-24 20:01 UTC, notconfusing commented on src/Components/Footer.js
> + 	 				<li><a href="">IRC</a></li>
Is that going to be our element channel?

2021-01-24 20:01 UTC, notconfusing commented on src/Components/Footer.js
> + 	 				<li><a href="">Github</a></li>
there are mutliple github repos, lets think about how to show that?

2021-01-24 20:01 UTC, notconfusing commented on src/Views/AboutView.js
> +        <figure>
NICE, very elegant.

2021-01-24 20:01 UTC, notconfusing commented on src/Views/DefaultView.js
> -        Expore further dynames of the gender gap in bibliographic content on Wikipedia
typo "dynames"

2021-01-24 21:03 UTC, sejalkhatri commented on src/Components/Footer.js
> + 	 				<li><a href="">IRC</a></li>
yes! Do we plan on keeping it active or not? 

If active then which configuration should we enable? 
option 1: Anyone who knows the room's link, apart from guests
option 2: Anyone who knows the room's link, including guests

If not active then we can direct to our discussion page on MediaWiki - https://www.mediawiki.org/wiki/Talk:Humaniki
or, 
on Phabricator

2021-01-24 21:12 UTC, sejalkhatri commented on src/Components/Footer.js
> + 	 				<li><a href="">Github</a></li>
We can redirect this link to Readme on Github (either Eugenia's repo or yours) where we provide information about how we maintain 2 repo for backend and frontend, and provide links!

2021-01-24 22:28 UTC, sejalkhatri commented on src/App.css
> -  position: -webkit-sticky;
Having a sticky footer is not the same as keeping the position sticky. I am looking for options to achieve that. 

An element with position: sticky; is positioned based on the user's scroll position. A sticky element toggles between relative and fixed , depending on the scroll position. It is positioned relative until a given offset position is met in the viewport - then it "sticks" in place (like position:fixed).

2021-01-31 19:44 UTC, TheEugeniaKim commented on src/Views/DefaultView.js
> +      <h6> Disctrribution of content of humans in all Wikimedia Projects </h6>
fix typo and (sum) to end (line 76)

2021-01-31 19:45 UTC, TheEugeniaKim commented on src/Views/DefaultView.js
> +      <p>All time, as of Aug'20</p>
LATEST SNAPSHOT

2021-01-31 19:46 UTC, TheEugeniaKim commented on src/Views/DefaultView.js
> +            For example, as of August 2020, only 17% of content in all Wikimedia projects including biographies on Wikipedia are about women.
LATEST SNAPSHOT (LATEST TOTAL COVERAGE)

2021-01-31 19:49 UTC, TheEugeniaKim requested changes
Looks good. Just need to resolve the container issue

2021-01-31 22:18 UTC, TheEugeniaKim approved these changes

2021-01-31 22:19 UTC, merged